---
title: "lizhouMethanol"
output: html_document
date: "2022-09-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(stringr)
library(dplyr)
library(tidyr)
library(ggvenn)
options(java.parameters = "-Xmx8000m")
library(xlsx)
library(ggsignif)
library(patchwork)
library(latex2exp)
library(readxl)
library(tidyr)
```

### unlabel

```{bash}
cd ../data/methanolUnlabel
src="/mnt/d/work/202208/AMXlabeledSearch"
Rscript $src/refineProteinFDR.R \
  -pro Isolife_MeSIP_Day.pro.txt \
  -psm Isolife_MeSIP_Day.psm.txt \
  -fdr 0.005 \
  -o Isolife_MeSIP_Day
Rscript $src/getSpectraCountInEachFT.R \
  -pro Isolife_MeSIP_Day.proRefineFDR.txt \
  -psm Isolife_MeSIP_Day.psm.txt \
  -o Isolife_MeSIP_Day
```

### label

```{bash}
cd ../data/methanolLabel
src="/mnt/d/work/202208/AMXlabeledSearch"
Rscript $src/refineProteinFDR.R \
  -pro Isolife_MeSIP_Day.pro.txt \
  -psm Isolife_MeSIP_Day.psm.txt \
  -fdr 0.01 \
  -o Isolife_MeSIP_Day
Rscript $src/getSpectraCountInEachFT.R \
  -pro Isolife_MeSIP_Day.proRefineFDR.txt \
  -psm Isolife_MeSIP_Day.psm.txt \
  -o Isolife_MeSIP_Day
Rscript $src/getLabelPCTinEachFT.R \
  -pro Isolife_MeSIP_Day.proRefineFDR.txt \
  -psm Isolife_MeSIP_Day.psm.txt \
  -thr 5 \
  -o Isolife_MeSIP_Day
```

```{r}
theme2 <- ggplot2::theme(
  # axis.text = ggplot2::element_blank(),
  # axis.ticks = ggplot2::element_blank(),
  # axis.title = ggplot2::element_blank(),
  panel.grid = ggplot2::element_blank(),
  panel.background = ggplot2::element_blank(),
  legend.key = ggplot2::element_blank(),
  panel.border = ggplot2::element_rect(
    fill = NA,
    color = "grey10",
    linetype = 1,
    size = 0.5
  ),
  text = ggplot2::element_text(size = 20),
  legend.position="top"
)
```

### labeled PSMs

```{r}
sp <- read.table(
  "../data/methanolLabel/Isolife_MeSIP_Day.LabelPCTcount.txt",
  sep = "\t",
  quote = "",
  header = T
)
sp <- sp[, str_detect(colnames(sp), "_PCTcount")]
d3 <- sp[, str_detect(colnames(sp), "_Day3")]
d3 <- unlist(d3)
d3 <- na.omit(d3)
d3 <- unlist(str_split(d3,","))
d3 <- d3[d3>5]
d8 <- sp[, str_detect(colnames(sp), "_Day8")]
d8 <- unlist(d8)
d8 <- na.omit(d8)
d8 <- unlist(str_split(d8,","))
d8 <- d8[d8>5]
drawDf <-
  data.frame(Time = c(rep("Day3", length(d3)), rep("Day8", length(d8))),
             Abundance = as.numeric(c(d3, d8)))

p4 <-
  ggplot2::ggplot(data = drawDf,
                  mapping = aes(x = Abundance, color = Time, fill = Time)) +
  ggplot2::geom_histogram(binwidth = 1,
                          position="identity", alpha=0.5) +
  xlab(TeX("$^{13}C\\,atom\\,abudance\\,(\\%)")) +
  ylab("Labeled protein count") +
  theme2
p4 <- p4 + scale_x_continuous(breaks = seq(0, 100, 10))

p2 <-
  ggplot(drawDf, aes(x = Time, y = Abundance, fill = Time)) +
  geom_boxplot(alpha = 0.80) +
  # geom_violin(alpha = 0.80) +
  ylim(0, 110) +
  geom_signif(
    comparisons = list(c("Day3", "Day8")),
    test = "wilcox.test",
    map_signif_level = TRUE,
    margin_top = 0.1,
    textsize = 5
  ) +
  ylab(TeX("$^{13}C\\,atom\\,abudance\\,(\\%)$")) + theme2 + guides(fill = "none")
```

### labeled proteins

```{r}
sp <- read.table(
  "../data/methanolLabel/Isolife_MeSIP_Day.LabelPCTcount.txt",
  sep = "\t",
  quote = "",
  header = T
)
proNames <- sp$proteinNames
sp <- sp[, str_detect(colnames(sp), "_labeledCount")]
sp <- sp[rowSums(sp) > 0, ]
fileNames <- colnames(sp)
fileNames <- str_split(fileNames, "\\.", simplify = T)[, 1]
fileNames <- str_split(fileNames, "_", simplify = T)[, 3]
proteinCount <- colSums(sp > 0)
psmCount <- colSums(sp)
df <-
  data.frame(
    Sample = fileNames,
    LabeldProteinCount = proteinCount,
    LabeldPSMCount = psmCount
  )
df <- group_by(df, Sample)
df <- summarise_all(df, sum)
df <- as.data.frame(arrange(df, Sample))
write.xlsx(df,
           "../result/methanol labeledProteinSummary.xlsx",
           row.names = F)

drawDf <- df
colnames(drawDf) <- c("Time", "Proteins", "PSMs")
drawDf$Time <- str_sub(drawDf$Time, 1, 4)
drawDf <-
  pivot_longer(drawDf,!Time, names_to = "Level", values_to = "Count")
p1 <-
  ggplot(drawDf[drawDf$Level == "Proteins",], aes(x = Time, y = Count, fill = Time)) +
  geom_boxplot(alpha = 0.80) +
  ylim(0, 300) +
  geom_signif(
    comparisons = list(c("Day3", "Day8")),
    test = "t.test",
    map_signif_level = TRUE,
    margin_top = 0.1,
    textsize = 5
  ) +
  ylab("Labeled protein count") + theme2 + guides(fill = "none")
# + ggtitle("Labeled proteins")
# p2 <- ggplot(drawDf[drawDf$Level=="PSMs",], aes(x = Time, y = Count)) +
#   geom_boxplot(alpha = 0.80) +
#   geom_signif(
#     comparisons = list(c("Day3", "Day8")),
#     test = "t.test",
#     map_signif_level = TRUE,
#     margin_top = 0.1,
#     textsize = 3
#   ) + theme2 + ggtitle("Labeled PSMs")

nProtein <- 1:nrow(sp)
Day8 <-
  sp[, str_detect(colnames(sp), "_Day8")]
Day8 <- nProtein[rowSums(Day8) > 0]
Day3 <-
  sp[, str_detect(colnames(sp), "_Day3")]
Day3 <- nProtein[rowSums(Day3) > 0]
pList <- list(Day3 = Day3 , Day8 = Day8)
p3 <- ggvenn(pList) + theme2
p <-
  p4 + p2 + p1 + p3 + plot_layout(ncol = 4)+plot_annotation(tag_levels = c('A'), tag_sep = '.') &
  theme(plot.tag.position = c(0, 1),
        plot.tag = element_text(
          size = 15,
          hjust = 0,
          vjust = 0
        ))
p
ggsave(
  "../result/Fig3 methanol labeled larger than 5 Day3 Day8 Venn and boxplot.pdf",
  width = 20,
  height = 5
)
```

```{bash}
conda create -n egg -c bioconda -c conda-forge eggnog-mapper=2.1.9
export EGGNOG_DATA_DIR=/ourdisk/hpc/prebiotics/yixiong/auto_archive_notyet/db/egg
download_eggnog_data.py 
cd /scratch/yixiong/lizhouCO2withPlantLabeled/fasta/

vim anno.sh

source ~/miniconda3/etc/profile.d/conda.sh
conda activate egg
# 2157,2,4751 archaea bacteria fungi's taxid
export EGGNOG_DATA_DIR=/ourdisk/hpc/prebiotics/yixiong/auto_archive_notyet/db/egg
emapper.py \
  -i db.faa -o anno \
  --sensmode more-sensitive \
  --tax_scope 2157,2,4751 \
  --cpu 0 --dbmem

chmod +x ./anno.sh
./anno.sh > anno.log.txt 2>&1 &
```


```{r}
anno <- read.table("../data/methanolLabel/anno.emapper.annotations",
             sep = "\t",
             quote = "",
             header = F)
annoName <- read.table(text = "query_name
seed_eggNOG_ortholog
seed_ortholog_evalue
seed_ortholog_score
eggNOG_OGs
max_annot_lvl
COG_cat
Description
Preferred_name
GOs
EC
KEGG_ko
KEGG_Pathway
KEGG_Module
KEGG_Reaction
KEGG_rclass
BRITE
KEGG_TC
CAZy
BiGG_Reaction
PFAMs")
colnames(anno) <- annoName$V1
write.xlsx(
  anno,
  "../result/proteinAnnotation.xlsx",
  row.names = F
)
```

```{r}
anno <- read_xlsx("../result/proteinAnnotation.xlsx")
# species <- anno[, c("query_name","eggNOG_OGs")]
# species <- separate(species,"eggNOG_OGs",paste0("V",1:7),",")
species <- anno$eggNOG_OGs
species <- lapply(species,str_remove,pattern="delta\\/epsilon subdivisions\\,")
species <- str_split(species,pattern = ",")
species <- lapply(species,str_remove,pattern=".*\\|")
species <- lapply(species,unique)
species <- plyr::ldply(species, rbind)
species <- species[,-1]
colnames(species) <- c("superkingdom","phylum","class","order","family","genus")
species <- cbind(Proteins=anno$query_name,species)

sp <- read.table(
  "../data/methanolLabel/Isolife_MeSIP_Day.LabelPCTcount.txt",
  sep = "\t",
  quote = "",
  header = T
)
proNames <- sp$proteinNames
sp <- sp[, str_detect(colnames(sp), "_PCTcount")]
Day8 <-
  sp[, str_detect(colnames(sp), "_Day8")]
Day8 <- apply(Day8,
              1,
              str_split,
              pattern = ",",
              simplify = F)
Day8Mean  <- lapply(Day8 , function(x) {
  x <- unlist(x)
  x <- na.omit(x)
  x <- as.numeric(x)
  x <- x[x > 5]
  mean(x)
})
Day8Count  <- lapply(Day8 , function(x) {
  x <- unlist(x)
  x <- na.omit(x)
  x <- as.numeric(x)
  x <- x[x > 5]
  length(x)
})
Day8Mean <- unlist(Day8Mean)
Day8Count <- unlist(Day8Count)
Day8ProNames <- proNames[Day8Count > 0]
Day8ProNames <- str_remove(Day8ProNames, "\\{")
Day8ProNames <- str_remove(Day8ProNames, "\\}")
Day8Count <- Day8Count[Day8Count > 0]
Day8Mean <- Day8Mean[!is.na(Day8Mean)]
drawDf <-
  data.frame(Proteins = Day8ProNames,
             Abundance = Day8Mean,
             Count = Day8Count)
drawDf <- separate_rows(drawDf, Proteins, sep = ",")
drawDf <- left_join(drawDf, species, c("Proteins" = "Proteins"))
drawDf$order <- str_remove(drawDf$order, "unclassified ")
top10 <- names(sort(table(drawDf$order), decreasing = T)[1:10])
drawDf$order[!(drawDf$order %in% top10)] <- "Others"
drawDf$order <- factor(drawDf$order, levels = c(top10, "Others"))
p5 <-
  ggplot(drawDf, aes(
    x = Abundance,
    y = Count,
    color = order,
    size = Count
  )) +
  geom_point() +
  xlab(TeX("$^{13}C\\,atom\\,abudance\\,(\\%)")) +
  ylab("Labeled protein count") +
  theme2 + guides(size = "none", color = guide_legend(override.aes = list(size =
                                                                            3))) +
  ggtitle("Day8")
```

```{r}
Day3 <-
  sp[, str_detect(colnames(sp), "_Day3")]
Day3 <- apply(Day3,
              1,
              str_split,
              pattern = ",",
              simplify = F)
Day3Mean  <- lapply(Day3 , function(x) {
  x <- unlist(x)
  x <- na.omit(x)
  x <- as.numeric(x)
  x <- x[x > 5]
  mean(x)
})
Day3Count  <- lapply(Day3 , function(x) {
  x <- unlist(x)
  x <- na.omit(x)
  x <- as.numeric(x)
  x <- x[x > 5]
  length(x)
})
Day3Mean <- unlist(Day3Mean)
Day3Count <- unlist(Day3Count)
Day3ProNames <- proNames[Day3Count > 0]
Day3ProNames <- str_remove(Day3ProNames, "\\{")
Day3ProNames <- str_remove(Day3ProNames, "\\}")
Day3Count <- Day3Count[Day3Count > 0]
Day3Mean <- Day3Mean[!is.na(Day3Mean)]
drawDf <-
  data.frame(Proteins = Day3ProNames,
             Abundance = Day3Mean,
             Count = Day3Count)
drawDf <- separate_rows(drawDf, Proteins, sep = ",")
drawDf <- left_join(drawDf, species, c("Proteins" = "Proteins"))
drawDf$order <- str_remove(drawDf$order, "unclassified ")
top10 <- names(sort(table(drawDf$order), decreasing = T)[1:10])
drawDf$order[!(drawDf$order %in% top10)] <- "Others"
drawDf$order <- factor(drawDf$order, levels = c(top10, "Others"))
p6 <-
  ggplot(drawDf, aes(
    x = Abundance,
    y = Count,
    color = order,
    size = Count
  )) +
  geom_point() +
  xlab(TeX("$^{13}C\\,atom\\,abudance\\,(\\%)")) +
  ylab("Labeled protein count") +
  theme2 + guides(size = "none", color = guide_legend(override.aes = list(size =
                                                                            3))) +
  ggtitle("Day3")
p <-
  p6 + p5 + plot_annotation(tag_levels = c('A'), tag_sep = '.') &
  theme(plot.tag.position = c(0, 1),
        plot.tag = element_text(
          size = 15,
          hjust = 0,
          vjust = 0
        ))
p
ggsave(
  "../result/Fig4 methanol labeled larger than 5 species 13C abundance and count.pdf",
  width = 25,
  height = 5
)
```


