---
title: "kegg map id barplot"
author: "xyz"
date: "2021/8/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(stringr)
library(Mfuzz)
library(tidyr)
library(KEGGREST)
```

```{r}
eset.f <- readRDS("eset.f.rds")
abundance <- rowSums(eset.f)
abundance <-
  data.frame(Protein = rownames(eset.f), Abundance = abundance)

clusterDf <- readRDS("proteinCluster10.rds")

speciesDf <- read_xlsx("../SuppTable 5 Protein Family Annotation(1).xlsx")
speciesDf <-
  data.frame(Protein = speciesDf[-1:-2, 1, drop = TRUE],
             Tax = speciesDf[-1:-2, 5, drop = TRUE])

drawDf <- left_join(clusterDf, speciesDf, by = c("Protein" = "Protein"))
drawDf <- left_join(drawDf, abundance, by = c("Protein" = "Protein"))
drawDf <- separate_rows(drawDf,Tax,sep = ",")
drawDf <- drawDf[drawDf$Tax!="NA",]

top10 <- drawDf[, 3:4]
top10 <- group_by(top10, Tax)
top10 <- summarise(top10, Abundance = sum(Abundance))
top10 <- arrange(top10, desc(Abundance))
top10 <- top10$Tax[1:10]

drawDf$Tax[!(drawDf$Tax %in% top10)] <- "Others"
drawDf$Cluster <- paste0("Cluster", drawDf$Cluster)
drawDf <- group_by(drawDf, Cluster, Tax)
drawDf <- summarise(drawDf, Abundance = sum(Abundance))

# pathway <- keggList("pathway")
pathwaydf <- read.table("map_title.tab",sep="\t",colClasses=c("character", "character"))
colnames(pathwaydf)<-c("id","term")
pathwaydf$id<-paste0("map",pathwaydf$id)
pathwaydf <- rbind(pathwaydf,id="Others",term="Others")
top10Term<- pathwaydf$term[match(top10,pathwaydf$id)]
top10Term <- c(top10Term,"Others")
drawDf$Tax<- pathwaydf$term[match(drawDf$Tax,pathwaydf$id)]

drawDf <-
  pivot_wider(drawDf, names_from = Cluster, values_from = Abundance)
drawDf[is.na(drawDf)] <- 0
drawDf[, -1] <- prop.table(as.matrix(drawDf[, -1]), 2) * 100
write.csv(drawDf, "cluster10 top 10 map id table.csv", row.names = F)

drawDf <- pivot_longer(drawDf, -Tax,names_to = "Cluster", values_to = "Abundance")
drawDf$Tax <- factor(drawDf$Tax,levels = c(top10Term))
drawDf$Cluster <- factor(drawDf$Cluster,levels = paste0("Cluster",1:10))

p <- ggplot(drawDf) +
  geom_bar(
    aes(Cluster, Abundance, fill = Tax),
    stat = "identity",
    width = 0.5,
    col = 'black'
  ) +
  coord_flip() +
  theme(axis.title.y = element_blank(), text = element_text(size = 10)) +
  ylab("Abundance (%)") +
  scale_fill_discrete(name = "Pathway")+
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p + ggsave("protein cluster abundance barplot map id.pdf",
           width = 8,
           height = 6)
```

