---
title: "KEGG Map id enrich"
author: "xyz"
date: "2021/8/17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(stringr)
library(tidyr)
library(clusterProfiler)
library(xlsx)
library(KEGGREST)
```

```{r}
eset.f <- readRDS("eset.f.rds")
abundance <- rowSums(eset.f)
abundance <-
  data.frame(Protein = rownames(eset.f), Abundance = abundance)

clusterDf <- readRDS("proteinCluster10.rds")

speciesDf <-
  read_xlsx("../SuppTable 5 Protein Family Annotation(1).xlsx")
speciesDf <-
  data.frame(Protein = speciesDf[-1:-2, 1, drop = TRUE],
             Tax = speciesDf[-1:-2, 4, drop = TRUE])

drawDf <-
  left_join(clusterDf, speciesDf, by = c("Protein" = "Protein"))
drawDf <-
  left_join(drawDf, abundance, by = c("Protein" = "Protein"))
drawDf <- separate_rows(drawDf, Tax, sep = ",")
drawDf <- drawDf[drawDf$Tax != "NA",]

# listDatabases()
# module <- keggList("module")
# module <- data.frame(id=str_sub(names(module),start=4),term=module)
# koToModule<-keggLink("ko", "module")
# koToModule<- data.frame(KO=str_sub(koToModule,4),MD=str_sub(names(koToModule),4))
# saveRDS(module,"module.rds")
# saveRDS(koToModule,"koToModule.rds")
module <- readRDS("module.rds")
koToModule <- readRDS("koToModule.rds")
drawDf <- right_join(drawDf, koToModule, by = c("Tax" = "KO"))

TERM2GENE <- data.frame(TERM = drawDf$MD, Gene = drawDf$Protein)
TERM2NAME <- module
colnames(TERM2NAME) <- c("TERM", "NAME")

getEnrichDf <- function(clusterID) {
  proteinID <- clusterDf$Protein[clusterDf$Cluster == clusterID]
  enrichResult <- enricher(
    proteinID,
    TERM2GENE = TERM2GENE,
    TERM2NAME = TERM2NAME,
    pvalueCutoff = 0.05,
    qvalueCutoff = 0.05
  )
  as.data.frame(enrichResult)
}

wb <- createWorkbook(type = "xlsx")
for (i in 1:10) {
  enrichResult <- getEnrichDf(i)
  if (nrow(enrichResult) > 0) {
    Sheet <- createSheet(wb, sheetName = paste0("Cluster", i))
    addDataFrame(
      enrichResult,
      Sheet,
      startRow = 1,
      startColumn = 1,
      row.names = F,
      col.names = T
    )
  }
}

saveWorkbook(wb, "KEGG Module id enrich.xlsx")
```

