---
title: "caculate subset combination correlation"
author: "xyz"
date: "2021/2/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### read data

```{r}
library(readxl)
library(tidyverse)
phy<-read.csv("../CellWallComponent.csv")
gene<-read.csv("../GeneExpressionData.csv")
# check
sum(phy$id==gene$id)
phy2<-separate(phy,id,c("GeneType","Stage","Repeat"),sep = "-")
gene2<-separate(gene,id,c("GeneType","Stage","Repeat"),sep = "-")
```

### Wrap gini function

```{r}
library(rsgcc)
library(qvalue)

getGiniMatrix<-function(mat){
  results <- cor.matrix(
  t(mat),
  cpus = 11,
  cormethod = "GCC",
  style = "all.pairs",
  pernum = 2000,
  sigmethod = "two.sided",
  output = "matrix"
)
  return(results)
}

getPhy2Gene<-function(mat,fileName){
  results<-getGiniMatrix(mat)
  r<-results$corMatrix
  # first 11 are genes, 15 are physiology
  r<-r[12:26,1:11]
  r <- cbind(r, physiology = rownames(r))
  r.gini <-
    pivot_longer(as.data.frame(r),
                 -physiology,
                 names_to = "gene",
                 values_to = "r")
  
  p<-results$pvalueMatrix
  p<-p[12:26,1:11]
  p <- cbind(as.data.frame(p), physiology = rownames(p))
  p.gini <-
    pivot_longer(as.data.frame(p),
                 -physiology,
                 names_to = "gene",
                 values_to = "p")
  q<-qvalue(p.gini$p,lambda=0)
  results.gini <- cbind(r.gini, p = p.gini$p, qOrFdr = q$qvalues)
  write.csv(results.gini, fileName, row.names = F)
}

getGene2Gene<-function(mat,fileName){
  results<-getGiniMatrix(mat)
  r<-results$corMatrix[12:26,12:26]
  r <- cbind(r, physiology = rownames(r))
  r.gini <-
    pivot_longer(as.data.frame(r),
                 -physiology,
                 names_to = "physiology2",
                 values_to = "r")
  
  p<-results$pvalueMatrix[12:26,12:26]
  p <- cbind(as.data.frame(p), physiology = rownames(p))
  p.gini <-
    pivot_longer(as.data.frame(p),
                 -physiology,
                 names_to = "physiology2",
                 values_to = "p")
  q<-qvalue(p.gini$p,lambda=0)
  results.gini <- cbind(r.gini, p = p.gini$p, qOrFdr = q$qvalues)
  write.csv(results.gini, fileName, row.names = F)
}
```

### N(GE) vs N + 1(CW)

V3 vs E4 + 
V3 vs R3 + 
S1 vs S2 + 
S2 vs S3

```{r}
getSub <- function(df, subs) {
  df2 <- data.frame()
  for (i in subs) {
    df2 <- rbind(df2, dplyr::filter(df, Stage == i))
  }
  return(df2)
}

gene3<-getSub(gene2,c("V3","V3","S1","S2"))
phy3 <- getSub(phy2,c("E4","R3","S2","S3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"N(GE) vs N + 1(CW)Physiology2Gene.gini.csv")
```

### N(GE) vs N + 2(CW): 

V3 vs R3 + 
S1 vs S3

```{r}
gene3<-getSub(gene2,c("V3","S1"))
phy3 <- getSub(phy2,c("R3","S3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"N(GE) vs N + 2(CW)Physiology2Gene.gini.csv")
```

###	Stages only NGE vs NCW:

-	V3 vs V3 + 
-	E4 vs E4 + 
-	R3 vs R3

```{r}
gene3<-getSub(gene2,c("V3","E4","R3"))
phy3 <- getSub(phy2,c("V3","E4","R3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Stages only NGE vs NCW.gini.csv")
```

### Stages only	NGE vs N+1CW:

-	V3 vs E4 + 
-	E4 vs R3

```{r}
gene3<-getSub(gene2,c("V3","E4"))
phy3 <- getSub(phy2,c("E4","R3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Stages only	NGE vs N+1CW.gini.csv")
```

### Stages only	NGE vs N+2CW:

V3 vs R3

```{r}
gene3<-getSub(gene2,c("V3"))
phy3 <- getSub(phy2,c("R3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Stages only	NGE vs N+2CW.gini.csv")
```

### Stage pairs NGE vs N+1CW: 

-	V3 vs E4

```{r}
gene3<-getSub(gene2,c("V3"))
phy3 <- getSub(phy2,c("E4"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Stage pairs NGE vs N+1CW V3 vs E4.gini.csv")
```


### Stage pairs NGE vs N+1CW: 

-	E4 vs R3

```{r}
gene3<-getSub(gene2,c("E4"))
phy3 <- getSub(phy2,c("R3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Stage pairs NGE vs N+1CW E4 vs R3 .gini.csv")
```

### Segments only; NvsN; N(GE) vs N(CW):
 
S1 vs S1 + 
S2 vs S2 + 
S3 vs S3 

```{r}
gene3<-getSub(gene2,c("S1","S2","S3"))
phy3 <- getSub(phy2,c("S1","S2","S3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Segments only; NvsN; N(GE) vs N(CW).gini.csv")
```

### Segments only; N(GE) vs N+1(CW); 

S1 vs S2 + 
S2 vs S3

```{r}
gene3<-getSub(gene2,c("S1","S2"))
phy3 <- getSub(phy2,c("S2","S3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Segments only; N(GE) vs N+1(CW).gini.csv")
```

### Segments only; N(GE) vs N+2 (CW): 

S1 vs S3

```{r}
gene3<-getSub(gene2,c("S1"))
phy3 <- getSub(phy2,c("S3"))
sum(gene3$GeneType==phy3$GeneType)
sum(gene3$Repeat==phy3$Repeat)
mat<-cbind(gene3[,-1:-3],phy3[,-1:-3])
getPhy2Gene(mat,"Segments only; N(GE) vs N+2 (CW).gini.csv")
```



