---
title: "impute NA by mice"
author: "xyz"
date: "2021/8/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mice)
library(ggplot2)
library(clusterCrit)
library(dtwclust)
```

  hierarchical cluster by Dynamic Time Warping (DTW) Distance  

  Ball Hall max diff
  
  C index min
  
  Dunn max

```{r}
data <-
  read.table(
    "old_version/time_merge.rpkm.tsv",
    head = T,
    sep = "\t",
    stringsAsFactors = F,
    row.names = 1
  )

NAcount<- rowSums(is.na(data))
eset<-data[NAcount<=2,]
eset<-mice(eset, maxit = 5, m = 5, seed = 1)
stripplot(eset, T30_35, pch = 19, xlab = "Imputation number")
eset<-complete(eset)
esetSTD<-t(scale(t(prop.table(as.matrix(eset),2))))

set.seed(9527)
hc <- tsclust(
  esetSTD,
  type = "hierarchical",
  k = 4L,
  distance = "sbd",
  trace = TRUE,
  control = hierarchical_control(method = "ward.D")
)
p <- plot(hc, type = "sc")
p <-
  p + scale_x_continuous(breaks = 1:8,
                         labels = colnames(eset.m),
                         name = "Time")
p <- p + ylab("Abundance")
p <- p + theme(
  text = element_text(size = 15),
  panel.background = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank()
)
p + ggsave("DTW Cluster.pdf", width = 12, height = 6)
table(hc@cluster)

fc <- tsclust(
  esetSTD,
  type = "fuzzy",
  k = 8L,
  distance = "dtw_basic",
  trace = TRUE
)
p <- plot(fc, type = "sc")

pc <- tsclust(
  CharTraj,
  type = "partitional",
  k = 4L,
  distance = "dtw_basic",
  centroid = "pam",
  seed = 3247L,
  trace = TRUE,
  args = tsclust_args(dist = list(window.size = 4L))
)
plot(hc, type = "sc")
table(hc@cluster)

# # HierarchicalTSClusters
# class(hc)
# methods(class = class(hc))
# attr(methods(class = class(hc)), 'info')
# showMethods(plot)
# getMethod("plot", c("TSClusters", "missing"))

ixs <- c()
for (c in 2:20) {
  set.seed(9527)
  cl <- tsclust(
    esetSTD,
    type = "hierarchical",
    k = c,
    distance = "dtw_basic",
    trace = F,
    control = hierarchical_control(method = "ward.D2")
  )
  ix <- unlist(intCriteria(esetSTD, cl@cluster, "all"))
  ixs <- c(ixs, ix)
}
ixname <- names(ixs[1:42])
ixs <- matrix(ixs, nrow = 19, byrow = T)
colnames(ixs) <- ixname
ixs <- as.data.frame(ixs)


df <- data.frame(x = 2:20, y = c(ixs$ball_hall))
p <- ggplot(df, aes(x = x, y = y)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters") +
  ylab("Ball Hall Index") +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p + ggsave("DTW Ball Hall Index.pdf", width = 8, height = 6)

df <- data.frame(x = 2:20, y = c(ixs$c_index))
p <- ggplot(df, aes(x = x, y = y)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters") +
  ylab("C Index") +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p + ggsave("DTW C Index.pdf", width = 8, height = 6)

df <- data.frame(x = 2:20, y = c(ixs$dunn))
p <- ggplot(df, aes(x = x, y = y)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters") +
  ylab("Dunn Index") +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p + ggsave("DTW Dunn Index.pdf", width = 8, height = 6)
```