# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_learnRcpp_rcpp_hello_world`)
}

rcpp_rcout <- function(v) {
    invisible(.Call(`_learnRcpp_rcpp_rcout`, v))
}

