---
title: "drawSignificant"
author: "xyz"
date: "2021/11/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[ggeffects](https://strengejacke.github.io/ggeffects/)

```{r}
library(ggplot2)
library(dplyr)
library(glmmTMB)
library(ggeffects)
```


```{r}
abundance <- read.csv("normalizedAbundance.csv")
sig <- read.csv("glmmArModel.csv")
sigExtrem <- sig[sig$qOrFDR <= 0.05, ]
sigExtrem <- arrange(sigExtrem, qOrFDR)
write.csv(sigExtrem, "sigExtrem.csv", row.names = F)
nrow(sigExtrem)

unlink("figureGlmm",recursive = TRUE)
dir.create("figureGlmm")

for (i in 1:nrow(sigExtrem)) {
  metabolite <- as.character(sigExtrem$metabolite)[i]
  AIC <- round(sigExtrem$AIC[i], 3)
  Estimate <- round(sigExtrem$Estimate[i], 3)
  FDR <- round(-log10(sigExtrem$qOrFDR[i]), 3)
  df <- cbind(abundance[, 1:3], Abundance = abundance[, metabolite])
  df$Time <- as.numeric(df$Time)
  df$Condition <- as.factor(df$Condition)
  df$RatID <- as.factor(df$RatID)
  m <-
    glmmTMB(
      formula = Abundance ~ Time + Condition + (1 | RatID),
      data = df,
      family = gaussian()
    )
  pred <- ggpredict(m, terms = c("Time", "Condition"))
  subtitle <-
    paste0("AIC==",
           AIC,
           "~~Estimate==",
           Estimate,
           "~~-log[10](FDR)==",
           FDR)
  p <- ggplot(df, aes(x = Time, y = Abundance, color = Condition)) +
    geom_point() +
    geom_line(aes(x, predicted, color = group),
              data = pred,
              inherit.aes = F) +
    geom_ribbon(
      aes(
        x,
        predicted,
        ymin = conf.low,
        ymax = conf.high,
        fill = group
      ),
      alpha = .1,
      data = pred,
      inherit.aes = F
    ) +
    guides(fill = "none") +
    theme(
      text = element_text(size = 15),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(
        fill = NA,
        color = "grey10",
        linetype = 1,
        size = 0.7
      )
    ) +
    labs(title = metabolite, subtitle = parse(text = subtitle))
  p
  ggsave(
    paste0("figureGlmm/top", i, " ", metabolite, ".pdf"),
    width = 8,
    height = 6
  )
}
```


