---
title: "barplot"
author: "xyz"
date: "2021/8/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(readxl)
library(stringr)
library(Mfuzz)
library(tidyr)
```

```{r}
data <-
  read.table(
    "../old_version/time_merge.rpkm.tsv",
    head = T,
    sep = "\t",
    stringsAsFactors = F,
    row.names = 1
  )
rt <- as.matrix(data)
eset <- new("ExpressionSet", exprs = rt)
eset.r <- filter.NA(eset, thres = 0.25)
eset.f <- fill.NA(eset.r, mode = "mean")
eset.f <- filter.std(eset.f, min.std = 0)
eset.m <- t(as.data.frame(eset.f))
abundance <- rowSums(eset.m)
abundance <-
  data.frame(Protein = rownames(eset.m), Abundance = abundance)

clusterDf <- readRDS("../mfuzz start from 4/proteinCluster7.rds")

speciesDf <- read_xlsx("../SuppTable 3 MAG Species.xlsx")
speciesDf <-
  data.frame(Protein = speciesDf[-1:-2, 1, drop = TRUE],
             Tax = speciesDf[-1:-2, 2, drop = TRUE])

drawDf <- left_join(clusterDf, speciesDf, by = c("Protein" = "Protein"))
drawDf$Order <- str_sub(str_extract(drawDf$Tax, "o__.*?;"), end = -2)
drawDf <- left_join(drawDf, abundance, by = c("Protein" = "Protein"))
drawDf$Order[is.na(drawDf$Order)] <- "Unknown"

top10 <- drawDf[, 4:5]
top10 <- group_by(top10, Order)
top10 <- summarise(top10, Abundance = sum(Abundance))
top10 <- arrange(top10, desc(Abundance))
top10 <- top10$Order[1:10]

drawDf$Order[!(drawDf$Order %in% top10)] <- "Others"
drawDf$Cluster <- paste0("Cluster", drawDf$Cluster)
drawDf <- group_by(drawDf, Cluster, Order)
drawDf <- summarise(drawDf, Abundance = sum(Abundance))

drawDf <-
  pivot_wider(drawDf, names_from = Cluster, values_from = Abundance)
drawDf[is.na(drawDf)] <- 0
drawDf[, -1] <- prop.table(as.matrix(drawDf[, -1]), 2) * 100
write.csv(drawDf, "cluster7table.csv", row.names = F)

drawDf <- pivot_longer(drawDf, -Order,names_to = "Cluster", values_to = "Abundance")
drawDf$Order <- factor(drawDf$Order,levels = c(top10,"Others"))
drawDf$Cluster <- factor(drawDf$Cluster,levels = paste0("Cluster",1:7))

p <- ggplot(drawDf) +
  geom_bar(
    aes(Cluster, Abundance, fill = Order),
    stat = "identity",
    width = 0.5,
    col = 'black'
  ) +
  coord_flip() +
  theme(axis.title.y = element_blank(), text = element_text(size = 10)) +
  ylab("Abundance (%)") +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p+ggsave("species cluster abundance barplot.pdf",width = 8,height = 6)
```

