---
title: "switch grass correlation"
author: "xyz"
date: "2021/2/1"
output: html_document
---

### normalize

```{r}
library(readxl)
# phy<-read.csv("new_data_wetchem.csv")
phy<-read_excel("new_data_wetchem.xlsx")
phy.scaled<-scale(phy[,-1])
gene<-read.csv("new_gene_expression.csv")
gene.abundance<-prop.table(as.matrix(gene[,-1]),2)
sum(phy$...1==gene$X)
```

### pearson

```{r}
library(psych)
library(tidyverse)
library(pheatmap)
results <-
  corr.test(phy.scaled, gene.abundance, method = "pearson", adjust = "none")
results.fdr <-
  corr.test(phy.scaled, gene.abundance, method = "pearson", adjust = "BH")
r <- results$r
r <- cbind(r, physiology = rownames(r))
r.pearson <-
  pivot_longer(as.data.frame(r),
               -physiology,
               names_to = "gene",
               values_to = "r")
p <- results$p
p <- cbind(p, physiology = rownames(p))
p.pearson <-
  pivot_longer(as.data.frame(p),
               -physiology,
               names_to = "gene",
               values_to = "p")
q <- results.fdr$p
q <- cbind(q, physiology = rownames(q))
q.pearson <-
  pivot_longer(as.data.frame(q),
               -physiology,
               names_to = "gene",
               values_to = "q")
sum(
  paste0(r.pearson$physiology,
         r.pearson$gene) == paste0(p.pearson$physiology,
                                   p.pearson$gene)
)
sum(
  paste0(r.pearson$physiology,
         r.pearson$gene) == paste0(q.pearson$physiology,
                                   q.pearson$gene)
)
results.pearson <- cbind(r.pearson, p = p.pearson$p, qOrFdr = q.pearson$q)
write.csv(results.pearson, "all.results.pearson.csv", row.names = F)
# Screening for genes with significant correlation
ix <- results.fdr$p
ix <- ix < 0.05
ix <- rowSums(ix) > 0
significance <- function(x) {
  if (x >= 0.05)
    ""
  else if (x >= 0.01)
    "*"
  else
    "**"
}
result.significance <-
  matrix(sapply(results$p[ix, ], significance), nrow = sum(ix))
pheatmap(
  results$r[ix, ],
  cluster_row = T,
  scale = "row",
  fontsize = 20,
  # pix=weight/height*300, col label's angle_col = "45"
  filename = "allPearsonPhysiologyGeneCorrelation.pdf",
  width = 10,
  height = 6,
  display_numbers = result.significance
)
```

### spearman

```{r}
results <-
  corr.test(phy.scaled, gene.abundance, method = "spearman", adjust = "none")
results.fdr <-
  corr.test(phy.scaled, gene.abundance, method = "spearman", adjust = "BH")
r <- results$r
r <- cbind(r, physiology = rownames(r))
r.spearman <-
  pivot_longer(as.data.frame(r),
               -physiology,
               names_to = "gene",
               values_to = "r")
p <- results$p
p <- cbind(p, physiology = rownames(p))
p.spearman <-
  pivot_longer(as.data.frame(p),
               -physiology,
               names_to = "gene",
               values_to = "p")
q <- results.fdr$p
q <- cbind(q, physiology = rownames(q))
q.spearman <-
  pivot_longer(as.data.frame(q),
               -physiology,
               names_to = "gene",
               values_to = "q")
sum(
  paste0(r.spearman$physiology,
         r.spearman$gene) == paste0(p.spearman$physiology,
                                   p.spearman$gene)
)
sum(
  paste0(r.spearman$physiology,
         r.spearman$gene) == paste0(q.spearman$physiology,
                                   q.spearman$gene)
)
results.spearman <- cbind(r.spearman, p = p.spearman$p, qOrFdr = q.spearman$q)
write.csv(results.spearman, "all.results.spearman.csv", row.names = F)
# Screening for genes with significant correlation
ix <- results.fdr$p
ix <- ix < 0.05
ix <- rowSums(ix) > 0
significance <- function(x) {
  if (x >= 0.05)
    ""
  else if (x >= 0.01)
    "*"
  else
    "**"
}
result.significance <-
  matrix(sapply(results$p[ix, ], significance), nrow = sum(ix))
pheatmap(
  results$r[ix, ],
  cluster_row = T,
  scale = "row",
  fontsize = 20,
  # pix=weight/height*300, col label's angle_col = "45"
  filename = "allspearmanPhysiologyGeneCorrelation.pdf",
  width = 10,
  height = 6,
  display_numbers = result.significance
)
```

### gini

```{r}
library(rsgcc)
# first 11 are genes, 15 are physiology
ncol(gene.abundance)
ncol(phy.scaled)
geneAndPhy <- cbind(gene.abundance, phy.scaled)
results <- cor.matrix(
  t(geneAndPhy),
  cpus = 11,
  cormethod = "GCC",
  style = "all.pairs",
  var1.id = c(1:11),
  var2.id = c(12:26),
  pernum = 2000,
  sigmethod = "two.sided",
  output = "matrix"
)

r<-results$corMatrix
# check
sum(colnames(r)==rownames(r))
sum(colnames(r)==colnames(geneAndPhy))
r<-r[12:26,1:11]
r <- cbind(r, physiology = rownames(r))
r.gini <-
  pivot_longer(as.data.frame(r),
               -physiology,
               names_to = "gene",
               values_to = "r")

p<-results$pvalueMatrix
# check
sum(colnames(p)==rownames(p))
sum(colnames(p)==colnames(geneAndPhy))
p<-p[12:26,1:11]
p <- cbind(p, physiology = rownames(p))
p.gini <-
  pivot_longer(as.data.frame(p),
               -physiology,
               names_to = "gene",
               values_to = "p")
q<-p.adjust(p.gini$p,"BH")
results.gini <- cbind(r.gini, p = p.gini$p, qOrFdr = q)
write.csv(results.gini, "all.results.gini.csv", row.names = F)

# Screening for genes with significant correlation
p.matrix<-results$pvalueMatrix[12:26,1:11]
q.matrix<-matrix(p.adjust(p.matrix,"BH"),nrow = nrow(p.matrix))
ix <- q.matrix
ix <- ix < 0.05
ix <- rowSums(ix) > 0
significance <- function(x) {
  if (x >= 0.05)
    ""
  else if (x >= 0.01)
    "*"
  else
    "**"
}
result.significance <-
  matrix(sapply(q.matrix[ix, ], significance), nrow = sum(ix))
pheatmap(
  results$corMatrix[12:26,1:11][ix, ],
  cluster_row = T,
  scale = "row",
  fontsize = 20,
  # pix=weight/height*300, col label's angle_col = "45"
  filename = "allGiniPhysiologyGeneCorrelation.pdf",
  width = 10,
  height = 6,
  display_numbers = result.significance
)
```

