---
title: "drawSignificant"
author: "xyz"
date: "2021/11/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
abundance <- read.csv("normalizedAbundance.csv")
sig <- read.csv("glmmArModel.csv")
sigExtrem <- sig[sig$qOrFDR<=0.01,]
sigExtrem <- arrange(sigExtrem,qOrFDR)

for (i in 1:nrow(sigExtrem)) {
  metabolite <- sigExtrem$metabolite[i]
  AIC <- round(sigExtrem$AIC[i], 3)
  Estimate <- round(sigExtrem$Estimate[i], 3)
  FDR <- round(-log10(sigExtrem$qOrFDR[i]), 3)
  df <- cbind(abundance[, 1:3], Abundance = abundance[, metabolite])
  subtitle <-
    paste0("AIC==",
           AIC,
           "~~Estimate==",
           Estimate,
           "~~-log[10](FDR)==",
           FDR)
  p <- ggplot(df, aes(x = Time, y = Abundance, color = Condition)) +
    geom_point() +
    geom_smooth(method = "glm",
                formula = y ~ poly(x, 1),
                se = T) +
    theme(
      text = element_text(size = 15),
      panel.grid = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(
        fill = NA,
        color = "grey10",
        linetype = 1,
        size = 0.7
      )
    ) +
    labs(title = metabolite, subtitle = parse(text = subtitle))
  p + ggsave(
    paste0("figures/top", i, " ", metabolite, ".pdf"),
    width = 8,
    height = 6
  )
}
```

