---
title: "glmm"
author: "xyz"
date: "2021/10/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(glmmTMB)
library(foreach)
library(doParallel)
```

# clean data

```{r}
df <-
  read.csv(
    "../Biomarkers Full Data Set_quant_BlkRemoved_missedinjRemoved_misslabeledRemoved_T_wMeta_TIC_urine_20210520.csv"
  )
meta <- df[, 1:10]
meta <- cbind(ID = paste0("X", 1:nrow(meta)), meta)
data <- df[, -1:-10]
rownames(data) <- meta$ID

data <- prop.table(as.matrix(data), 1)
data <- data[,colSums(data)!=0]
data <- prop.table(data,2)
Time <- meta$ATTRIBUTE_month_day
TimeLevel <- rep(0, length(Time))
TimeLevel[Time == "Sept_10"] <- 1
TimeLevel[Time == "Sept_16"] <- 2
TimeLevel[Time == "Sept_23"] <- 3
TimeLevel[Time == "Sept_30"] <- 4
TimeLevel[Time == "Oct_7"] <- 5
TimeLevel[Time == "Oct_21"] <- 6
TimeLevel[Time == "Oct_28"] <- 7
TimeLevel[Time == "Nov_12"] <- 8
TimeLevel[Time == "Nov_25"] <- 9
data <-
  cbind.data.frame(Time = TimeLevel,
                   Condition = meta$ATTRIBUTE_condition,
                   RatID=meta$ATTRIBUTE_mouse_number,
                   data)
data <- arrange(data, Time, RatID,Condition)
data <- data[data$Condition!="isoproterenol",]
data$Time<-as.factor(data$Time)
data$RatID<-as.factor(data$RatID)
```

# run model

```{r}
# wrap function to decrease parameters
getGlmmResult <- function(data, formula) {
  data <- data
  formula <- formula
  getSummary <- function(data, metabolite, formula) {
    df <- cbind(metabolite = data[, metabolite], data[, 1:3])
    model <-
      glmmTMB(formula = formula,
              data = df,
              family = gaussian())
    results <- summary(model)
    return(results)
  }
  getGlmmResult <- function(metabolite) {
    tryCatch({
      results <- getSummary(data, metabolite, formula)
      AIC <- results[["AICtab"]][["AIC"]]
      coefficients <- results[["coefficients"]][["cond"]]
      ENV <- rownames(coefficients)
      rownames(coefficients) <- NULL
      results <- cbind(
        metabolite = metabolite,
        ENV = ENV,
        AIC = AIC,
        coefficients
      )
      return(results)
    },
    error = function(e) {
      print(paste(e, "error"))
      return(NA)
    })
  }
  return(getGlmmResult)
}

formula1 <-
  formula(metabolite ~ ar1(Time + 0 | RatID) + Condition)
formula2 <-
  formula(metabolite ~ ar1(Time + 0 |  Condition) + Condition)
getGlmmResultArModel <- getGlmmResult(data, formula1)

cl <- makeCluster(detectCores() / 2)
registerDoParallel(cl)
results1 <- foreach(metabolite = colnames(data[,-1:-3]),
                    .packages = c("glmmTMB")) %dopar%
  getGlmmResultArModel(metabolite)
stopCluster(cl)
saveRDS(results1, "glmmAR1Result.rds")

results3 <- as.data.frame(do.call(rbind, results1))
# -473.6929
mean(as.numeric(results3$AIC), na.rm = T)
rownames(results3) <- NULL
results3 <- dplyr::filter(results3, ENV != "(Intercept)")
results3 <- results3[, -2]
results3 <-
  results3[!is.na(results3$AIC) & results3$`Pr(>|z|)` != "NaN", ]
results3 <- cbind(results3, qOrFDR = p.adjust(results3$`Pr(>|z|)`, "BH"))
write.csv(results3, "glmmArModel.csv", row.names = F)
```

