---
title: "Metabolomics all samples"
author: "xyz"
date: "2021/9/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(Mfuzz)
library(ggplot2)
library(clusterCrit)
library(tidyr)
library(dplyr)
```

```{r}
df <-
  read.csv(
    "../Biomarkers Full Data Set_quant_BlkRemoved_missedinjRemoved_misslabeledRemoved_T_wMeta_TIC_urine_20210520.csv"
  )
meta <- df[, 1:10]
meta <- cbind(ID = paste0("X", 1:nrow(meta)), meta)
data <- df[, -1:-10]
rownames(data) <- meta$ID

data <- prop.table(as.matrix(data), 1)
Time <- meta$ATTRIBUTE_month_day
TimeLevel <- rep(0, length(Time))
TimeLevel[Time == "Sept_10"] <- 1
TimeLevel[Time == "Sept_16"] <- 2
TimeLevel[Time == "Sept_23"] <- 3
TimeLevel[Time == "Sept_30"] <- 4
TimeLevel[Time == "Oct_7"] <- 5
TimeLevel[Time == "Oct_21"] <- 6
TimeLevel[Time == "Oct_28"] <- 7
TimeLevel[Time == "Nov_12"] <- 8
TimeLevel[Time == "Nov_25"] <- 9
data <-
  cbind.data.frame(Time = TimeLevel,
                   RatID = paste0("Rat",meta$ATTRIBUTE_mouse_number),
                   data)
data <- arrange(data, Time, RatID)
data <- group_by(data, Time, RatID)
data <- summarise(data, across(everything(), mean))
data <-
  pivot_wider(
    data,
    Time,
    names_from = RatID,
    values_from = !(Time:RatID),
    names_sep = "__"
  )
data<-as.matrix(data)
data[data==0]<-NA

rt <- as.matrix(t(data[,-1]))
eset <- new("ExpressionSet", exprs = rt)
eset.r <- filter.NA(eset, thres = 0.5)
eset.f <- fill.NA(eset.r, mode = "knnw")
eset.f <- filter.std(eset.f, min.std = 0.00001)
eset.s <- standardise(eset.f)
eset.m <- t(as.data.frame(eset.s))
dim(eset.m)

m <- mestimate(eset.s)
ixs <- c()
for (c in 2:20) {
  set.seed(9527)
  cl <- mfuzz(eset.s, c = c, m = m)
  ix <- unlist(intCriteria(eset.m,cl$cluster,"all"))
  ixs <- c(ixs, ix)
}
ixname <- names(ixs[1:42])
ixs <- matrix(ixs, ncol = 42, byrow = T)
colnames(ixs) <- ixname
ixs <- as.data.frame(ixs)
saveRDS(ixs,"ixsRAT.rds")
bestK<-c()
for (i in ixname){
  bestK<-c(bestK,bestCriterion(ixs[,i],i))
}
bestK<-bestK+1
names(bestK)<-ixname

#     ball_hall   banfeld_raftery           c_index calinski_harabasz 
#                 3                20                20                 2 
#    davies_bouldin         det_ratio              dunn             gamma 
#                14                 7                 6                20 
#            g_plus             gdi11             gdi12             gdi13 
#                20                 6                 6                 6 
#             gdi21             gdi22             gdi23             gdi31 
#                 7                 6                 6                 2 
#             gdi32             gdi33             gdi41             gdi42 
#                 3                 3                 3                 3 
#             gdi43             gdi51             gdi52             gdi53 
#                 3                 2                 2                 2 
#          ksq_detw     log_det_ratio      log_ss_ratio       mcclain_rao 
#                 7               NaN                 3                20 
#               pbm    point_biserial          ray_turi   ratkowsky_lance 
#                 2                20                14                 2 
#      scott_symons           sd_scat            sd_dis             s_dbw 
#               NaN                20                 3               NaN 
#        silhouette               tau           trace_w         trace_wib 
#                 2                 5                 3                19 
# wemmert_gancarski          xie_beni 
#                 2                 6
bestK

ixsLong <- as.data.frame(scale(ixs))
ixsLong <- cbind(x = 2:20, ixsLong)
ixsLong <- pivot_longer(ixsLong, -x, names_to = "Index", values_to = "y")

p <- ggplot(ixsLong, aes(x = x, y = y)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters") +
  ylab("Index") +
  scale_x_continuous(breaks = seq(2,20,by=2))+
  facet_wrap(vars(Index), ncol = 5) +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )

p+ggsave("All Indexes.pdf",width = 12,height = 12)

df<-data.frame(x=2:20,y=c(ixs$ball_hall))
p<-ggplot(df,aes(x=x,y=y))+
  geom_line()+
  geom_point()+
  xlab("Number of clusters")+
  ylab("Total within-clusters sum of squares")+
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ))
p+ggsave("ball_hall Index.pdf",width = 8,height = 6)
```

```{r}
set.seed(9527)
cl <- mfuzz(eset.s, c = 3, m = m)
pdf("mfuzz clust 3.pdf",width = 12,height = 4)
mfuzz.plot(
  eset.s,
  cl,
  mfrow = c(1, 3),
  new.window = FALSE,
  min.mem = 0.5
)
dev.off()
cl3<-cl$cluster
cl3<-data.frame(Metabolite=names(cl3),Cluster=cl3)
saveRDS(cl3,"cl.rds")

Cluster3<-cl$cluster
Cluster3<-data.frame(Metabolite=names(Cluster3),Cluster=Cluster3)
sum(rownames(cl$membership)==Cluster3$Metabolite)
Cluster3<-cbind(Cluster3,cl$membership)
Cluster3$MaxMembership<-apply(Cluster3[,-1:-2],1,max)
write.csv(Cluster3,"MetaboliteCluster3.csv",row.names = F)
```

