#! /bin/sh
module load \
    CMake/3.15.3-GCCcore-8.3.0 \
    OpenMPI/3.1.4-GCC-8.3.0 \
    gperftools/2.7.90-GCCcore-8.3.0
case $1 in
"clean")
    rm -rf build
    mkdir build
    rm -rf bin
    mkdir bin
    ;;
"build")
    cd build
    cmake -DCMAKE_BUILD_TYPE=Release ..
    make -j6
    ;;
"debug")
    cd build
    cmake -DCMAKE_BUILD_TYPE=Debug ..
    make -j6
    ;;
"make")
    cd build
    make
    ;;
"run")
    cd timeCompare
    time ../bin/SiprosV3omp -c SiproConfig.N15_0Pct.cfg -f AMD_DynamicSIP_SampleD_TimePoint0_BRmixed_WC_Velos_OrbiMS2_Run2_020210_09.FT2
    # ./SiprosV3mpi
    ;;
*)
    ./make "build"
    ;;
esac
