---
title: "get Best Cluster Number by clusterCrit"
author: "xyz"
date: "2021/8/9"
output: html_document
---

```{r}
library(Mfuzz)
library(ggplot2)
library(clusterCrit)
library(tidyr)
library(readxl)
```


```{r}
data <-
  read.table(
    "../final_age_8stages_rpkm_0801.txt",
    head = T,
    sep = "\t",
    stringsAsFactors = F,
    row.names = 1
  )
rt <- as.matrix(data)
rt.abundance<-rowSums(rt)
rt.abundance<-rt.abundance/sum(rt.abundance)*100
rt<-rt[rt.abundance>0.001,]
eset <- new("ExpressionSet", exprs = rt)
eset.r <- filter.NA(eset, thres = 0.25)
eset.f <- fill.NA(eset.r, mode = "mean")
eset.f <- filter.std(eset.f, min.std = 0)
eset.s <- standardise(eset.f)
eset.m <- t(as.data.frame(eset.s))
m <- mestimate(eset.s)
```
# get 42 indexes

```{r}
ixs <- c()
for (c in 2:20) {
  set.seed(9527)
  cl <- mfuzz(eset.s, c = c, m = m)
  print(paste(c,"mfuzz done"))
  ix <- unlist(intCriteria(eset.m,cl$cluster,"all"))
  print(paste(c,"index done"))
  ixs <- c(ixs, ix)
}
ixname <- names(ixs[1:42])
```

# get best k from 2

```{r}
ixs <-readRDS("ixs.rds")
ixname <- colnames(ixs)
bestK<-c()
for (i in ixname){
  bestK<-c(bestK,bestCriterion(ixs[,i],i))
}
bestK<-bestK+1
names(bestK)<-ixname

#         ball_hall   banfeld_raftery           c_index calinski_harabasz    davies_bouldin 
#                 3                20                 3                 3                 2 
#         det_ratio              dunn             gamma            g_plus             gdi11 
#                19                 2                 3                20                 2 
#             gdi12             gdi13             gdi21             gdi22             gdi23 
#                 2                 2                 3                 8                10 
#             gdi31             gdi32             gdi33             gdi41             gdi42 
#                 2                 2                 2                 2                 2 
#             gdi43             gdi51             gdi52             gdi53          ksq_detw 
#                 2                 2                 2                 2                 3 
#     log_det_ratio      log_ss_ratio       mcclain_rao               pbm    point_biserial 
#               NaN                 3                20                 3                18 
#          ray_turi   ratkowsky_lance      scott_symons           sd_scat            sd_dis 
#                 2                 2               NaN                20                 2 
#             s_dbw        silhouette               tau           trace_w         trace_wib 
#               NaN                 2                 2                 3                13 
# wemmert_gancarski          xie_beni 
#                 2                 2 
bestK

```

# get best k from 4

```{r}
ixs <-readRDS("ixs.rds")
ixname <- colnames(ixs)
ixs <-ixs[-1:-2,]
bestK<-c()
for (i in ixname){
  bestK<-c(bestK,bestCriterion(ixs[,i],i))
}
bestK<-bestK+3
names(bestK)<-ixname

#         ball_hall   banfeld_raftery           c_index calinski_harabasz    davies_bouldin 
#                10                20                20                 4                 7 
#         det_ratio              dunn             gamma            g_plus             gdi11 
#                19                 6                20                20                 6 
#             gdi12             gdi13             gdi21             gdi22             gdi23 
#                 6                 6                 5                 6                 6 
#             gdi31             gdi32             gdi33             gdi41             gdi42 
#                 4                 4                 5                 5                 5 
#             gdi43             gdi51             gdi52             gdi53          ksq_detw 
#                 5                 4                 4                 4                 7 
#     log_det_ratio      log_ss_ratio       mcclain_rao               pbm    point_biserial 
#               NaN                 6                20                 4                20 
#          ray_turi   ratkowsky_lance      scott_symons           sd_scat            sd_dis 
#                 5                 4               NaN                20                 4 
#             s_dbw        silhouette               tau           trace_w         trace_wib 
#               NaN                 4                 4                 6                18 
# wemmert_gancarski          xie_beni 
#                 7                 6
bestK                

ixsLong <- as.data.frame(scale(ixs))
ixsLong <- cbind(x = 4:20, ixsLong)
ixsLong <- pivot_longer(ixsLong, -x, names_to = "Index", values_to = "y")

p <- ggplot(ixsLong, aes(x = x, y = y)) +
  geom_line() +
  geom_point() +
  xlab("Number of clusters") +
  ylab("Index") +
  scale_x_continuous(breaks = seq(2,20,by=2))+
  facet_wrap(vars(Index), ncol = 5) +
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    )
  )
p+ggsave("All Indexes.pdf",width = 12,height = 12)

df<-data.frame(x=4:20,y=c(ixs$sd_dis))
p<-ggplot(df,aes(x=x,y=y))+
  geom_line()+
  geom_point()+
  xlab("Number of clusters")+
  ylab("SD Dis Index")+
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ))
p+ggsave("sd_dis Index.pdf",width = 8,height = 6)

df<-data.frame(x=4:20,y=c(ixs$silhouette))
p<-ggplot(df,aes(x=x,y=y))+
  geom_line()+
  geom_point()+
  xlab("Number of clusters")+
  ylab("Silhouette Index")+
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ))
p+ggsave("silhouette.pdf",width = 8,height = 6)

df<-data.frame(x=4:20,y=c(ixs$trace_wib))
p<-ggplot(df,aes(x=x,y=y))+
  geom_line()+
  geom_point()+
  xlab("Number of clusters")+
  ylab("trace_wib Index")+
  theme(
    text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.background = element_blank(),
    panel.border = element_rect(
      fill = NA,
      color = "grey10",
      linetype = 1,
      size = 1.
    ))
p+ggsave("trace_wib.pdf",width = 8,height = 6)
```

# draw cluster

```{r}
set.seed(9527)
cl <- mfuzz(eset.s, c = 3, m = m)
pdf("mfuzz clust 3.pdf",width = 15,height = 5)
mfuzz.plot(
  eset.s,
  cl,
  mfrow = c(1, 3),
  new.window = FALSE,
  min.mem = 0.5
)
dev.off()
proteinCluster3<-cl$cluster
proteinCluster3<-data.frame(Protein=names(proteinCluster3),Cluster=proteinCluster3)
saveRDS(proteinCluster3,"proteinCluster3.rds")

set.seed(9527)
cl <- mfuzz(eset.s, c = 4, m = m)
pdf("mfuzz clust 4.pdf",width = 15,height = 9)
mfuzz.plot(
  eset.s,
  cl,
  mfrow = c(2, 2),
  new.window = FALSE,
  min.mem = 0.5
)
dev.off()
proteinCluster4<-cl$cluster
proteinCluster4<-data.frame(Protein=names(proteinCluster4),Cluster=proteinCluster4)
saveRDS(proteinCluster4,"proteinCluster4.rds")
```

